---
# tasks file for swqk8smaster
#- name: Include distribution specifc vars
#  include_vars: '{{ ansible_distribution }}.yml'

- name: CentOS install
  include: centos_install.yml
  when: ansible_distribution == 'CentOS'

- name: Ubuntu install
  include: ubuntu_install.yml
  when: ansible_distribution == 'Ubuntu'
